enhance DNS
XTLS/Xray-core pull request #234
Opened 2021-02-04 08:35 UTC by JimhHan

- 加了 DNS 查询日志
- 修了 DoH 遗留问题

2021-02-11 10:12 UTC, AkinoKaede commented on infra/conf/log.go
> +	DNSLog    bool   `json:"dns_log"`
dns_log 应该按小驼峰命名法命名为 dnsLog

2021-02-19 18:13 UTC, rurirei commented
>> 将每一个建立的系统连接，尝试通过内置DNS服务器解析地址后，使用IP地址建立连接

least Android system do remoteserver-domain parsing, rather v2ray-core (AndroidLibV2ray), as it excepts Android.

2021-02-19 18:23 UTC, rurirei requested changes

2021-02-19 18:23 UTC, rurirei commented on core/xray.go
> +	internet.SetSystemDialerDNS(server.GetFeature(dns.ClientType()).(dns.Client))
```golang
        if runtime.GOOS != "android" { 
 		...
 	}
```

2021-02-20 00:18 UTC, JimhHan commented
@rurirei 
很抱歉，我未能理解您的意思。但是，这个功能默认不启用。

2021-02-20 01:08 UTC, rurirei commented
@JimhHan 
https://github.com/2dust/v2rayNG/blob/master/AndroidLibV2rayLite/VPN/vpnservice_support.go#L149

2021-03-05 08:45 UTC, rprx commented
这个可以合并了吗

2021-03-05 09:48 UTC, JimhHan commented
可以了

2021-03-06 14:51 UTC, rprx commented
需要 resolve conflicts

2021-03-06 15:31 UTC, rprx commented
`TransportLayerProxy` 被干掉了

2021-03-06 16:12 UTC, merged

2021-03-06 16:13 UTC, rprx commented
感谢 PR，请补充文档说明

2021-03-06 16:27 UTC, rprx commented
重开一个 PR 吧。。。

2021-04-01 03:29 UTC, elvisw commented
v2fly的`transportLayer`我试了没法把h2通过http代理发送，而xray的`sockopt.dialerProxy`我刚测试成功了，这下不需要用dokodemo-door桥接了