Github Action auto Release
XTLS/Xray-core pull request #251
Opened 2021-02-13 14:32 UTC by kokeri

基本覆盖能支持的所有平台。目前使用go1.16.rc1编译。
.github/build/{version,preversion,changelog}分别表示版本发布，prerelease发布及更新日志。同时有test功能。geoip.dat, geosite.dat来自v2fly。文件修改时间重置为UTC+0 2020.01.01 00:00.
prerelease触发条件为preversion，不附带changelog，同时对已有包不覆盖。
release触发条件为version，带有changelog，同时会删除已有同名tag及其release（包括package）（为了更新发布pre版本时所携带的随机分支储存的代码）。
prerelease与release均可手动触发。

2021-02-13 14:35 UTC, AkinoKaede commented
@kokeri 我觉得还是先 release 后再由 Action 上传比较好

2021-02-13 16:38 UTC, xinb commented
> @kokeri 我觉得还是先 release 后再由 Action 上传比较好

已修改，触发条件为release或prerelease。取消删除prerelease tag后重建，改为覆盖bin文件。
增加对每个修改的Autobuild，编译的文件保存到Action 目录，便于获取随代码更改而产生的最新二进制。
发布效果见：https://github.com/x2xi/Xray-core/actions/runs/564070864
目前理想release发布工作流程：添加pre release->编辑changelog->修改为release->完成发布。可不进行pre release发布。
tips: changelog的提交为增加内容而非对note的覆写。
发布效果见：https://github.com/x2xi/Xray-core/releases/tag/v1.3.0
修改参见https://github.com/x2xi/Xray-core，由于资源限制原因，修改都会在此仓库进行，确认无误后再并入到提交了Pull Request的仓库。

2021-02-13 22:42 UTC, rprx commented
感谢 PR，需要以下修改：

1. 压缩包改为以 `Xray` 开头，首字母大写
2. 压缩包内放入 LICENSE 文件
3. mips 的 softfloat 打包进 mips 即可

关于自动编译 Artifacts：

1. 可否与 release 的发布格式相同？
2. 可否将 `Custom` 改为 `7afe274` 以区分？

Go 1.16 正式发布后可以用这个编译流程

2021-02-13 23:38 UTC, AkinoKaede commented
> > @kokeri 我觉得还是先 release 后再由 Action 上传比较好
> 
> 已修改，触发条件为release或prerelease。取消删除prerelease tag后重建，改为覆盖bin文件。
> 增加对每个修改的Autobuild，编译的文件保存到Action 目录，便于获取随代码更改而产生的最新二进制。
> 发布效果见：https://github.com/x2xi/Xray-core/actions/runs/564070864
> 目前理想release发布工作流程：添加pre release->编辑changelog->修改为release->完成发布。可不进行pre release发布。
> tips: changelog的提交为增加内容而非对note的覆写。
> 发布效果见：https://github.com/x2xi/Xray-core/releases/tag/v1.3.0
> 修改参见https://github.com/x2xi/Xray-core 由于资源限制原因，修改都会在此仓库进行，确认无误后再并入到提交了Pull Request的仓库。

或许应该使用 svenstaro/upload-release-action@v2 上传文件而不修改 Changlog

2021-02-14 17:31 UTC, kokeri commented
> 感谢 PR，需要以下修改：
> 
> 1. 压缩包改为以 `Xray` 开头，首字母大写
> 2. 压缩包内放入 LICENSE 文件
> 3. mips 的 softfloat 打包进 mips 即可
> 
> 关于自动编译 Artifacts：
> 
> 1. 可否与 release 的发布格式相同？
> 2. 可否将 `Custom` 改为 `7afe274` 以区分？
> 
> Go 1.16 正式发布后可以用这个编译流程
1. 2. 已修改
目前将 softfloat 打包进 mips 是采取一个包里面包含 hardfloat 和 softfloat 两个包的方式。我认为此方案有所不便，但是目前没想到更好的办法。

自动编译 :
1.
由于上传包时 Github 会压缩为 zip ，因此和 release 格式会有所差别。可以选择按照之前的旧方案，或者在自动生成的包中包括和release相同的 zip 及 dgst 文件。
2.
不是很清楚将 ’Custom‘  改为 '7afe274' 是指哪一位置。

> > > @kokeri 我觉得还是先 release 后再由 Action 上传比较好
> > 
> > 
> > 已修改，触发条件为release或prerelease。取消删除prerelease tag后重建，改为覆盖bin文件。
> > 增加对每个修改的Autobuild，编译的文件保存到Action 目录，便于获取随代码更改而产生的最新二进制。
> > 发布效果见：https://github.com/x2xi/Xray-core/actions/runs/564070864
> > 目前理想release发布工作流程：添加pre release->编辑changelog->修改为release->完成发布。可不进行pre release发布。
> > tips: changelog的提交为增加内容而非对note的覆写。
> > 发布效果见：https://github.com/x2xi/Xray-core/releases/tag/v1.3.0
> > 修改参见https://github.com/x2xi/Xray-core 由于资源限制原因，修改都会在此仓库进行，确认无误后再并入到提交了Pull Request的仓库。
> 
> 或许应该不修改 Changlog

暂时未修改Changelog部分，因为Changelog部分修改比较方便且不需要多次测试，因此在编译、上传流程修改后再考虑。

2021-02-14 22:41 UTC, AkinoKaede commented
@kokeri Custom 是指 core.go 中的 build  
https://github.com/XTLS/Xray-core/blob/573b7807c099dc268a0d3a3d011539bb44f2f314/core/core.go#L22
非 Release 中可以改为 Commit ID 以方便开发者区分

2021-02-14 22:47 UTC, AkinoKaede commented
@kokeri LICENSE 文件可直接从 GITHUB_WORKSPACE 中获取，无需使用 wget 下载

2021-02-15 04:47 UTC, kokeri commented
> @kokeri LICENSE 文件可直接从 GITHUB_WORKSPACE 中获取，无需使用 wget 下载

感谢指点，已修改.

2021-02-15 06:14 UTC, AkinoKaede commented
直接提交了，其实版本用 github.ref 获取 tag 就行

2021-02-15 07:32 UTC, kokeri commented
> 直接提交了，其实版本用 github.ref 获取 tag 就行

感谢，目前调整了工作流程，功能不变，仅保留release与test文件。添加注释。

2021-02-15 08:24 UTC, SekiBetu commented
文件名后要不要增加hash校验码
每次触发编译的时候要不要更新依赖

2021-02-15 08:25 UTC, AkinoKaede commented
> 文件名后要不要增加hash校验码
> 每次触发编译的时候要不要更新依赖

hash 在 dgst 里面
依赖可用 dependabot 管理

2021-02-15 08:35 UTC, SekiBetu commented
> > 文件名后要不要增加hash校验码
> > 每次触发编译的时候要不要更新依赖
> 
> hash 在 dgst 里面
> 依赖可用 dependabot 管理

github.com/miekg/dns v1.1.37 这个依赖已经有新版本了，dependabot 好像没反应？

2021-02-15 08:36 UTC, AkinoKaede commented
@SekiBetu 我只是说可是 没说用了

2021-02-15 08:43 UTC, SekiBetu requested changes

2021-02-15 08:43 UTC, SekiBetu commented on .github/workflows/release.yml
> +      - name: Prepare package for Linux #添加ststemd
捉个虫

2021-02-15 08:44 UTC, SekiBetu commented on .github/workflows/release.yml
> +      - name: Prepare package for Linux #添加ststemd
#添加ststemd → #添加systemd

2021-02-15 08:49 UTC, SekiBetu approved these changes

2021-02-15 08:49 UTC, SekiBetu commented on .github/workflows/test.yml
> +      - name: Prepare package for Linux #添加ststemd
```suggestion
      - name: Prepare package for Linux #添加systemd
```

2021-02-15 08:49 UTC, SekiBetu commented on .github/workflows/release.yml
> +      - name: Prepare package for Linux #添加ststemd
```suggestion
      - name: Prepare package for Linux #添加systemd
```

2021-02-15 13:15 UTC, AkinoKaede commented
为何移除 systemd 文件呢

2021-02-15 13:17 UTC, rprx commented
@AkinoKaede 应该是看到了我在群里说的话，是要移除的，因为 Xray-install 内置了，还在此基础上实现了更多功能

2021-02-15 13:29 UTC, JimhHan commented on .github/workflows/release.yml
> +          go-version: 1.16.0-rc1
应使用稳定版本的golang编译

2021-02-15 13:31 UTC, AkinoKaede commented
prerelease 改为 release 时会重复触发，所以移除

2021-02-15 13:32 UTC, xinb commented on .github/workflows/release.yml
> +          go-version: 1.16.0-rc1
已知晓，目前认为会在1.16.0发布后合并，且对M1单独处理不便，因此采用rc1。

2021-02-15 13:34 UTC, xinb commented
> prerelease 改为 release 时会重复触发，所以移除

参见：https://docs.github.com/cn/actions/reference/events-that-trigger-workflows
可尝试使用published或created，我还没有测试过这两种有何区别。

2021-02-15 13:40 UTC, JimhHan commented
似乎有一些测试无法通过，我来修复一下

2021-02-15 14:09 UTC, kokeri commented
prerelease 改为 published ，prerelease 或 release 会触发，修改时不触发

2021-02-15 14:10 UTC, rprx commented
@kokeri 对了，需要把时间置为 UTC 2021-01-01 00:00:00（重点是 2021）

2021-02-16 23:48 UTC, AkinoKaede reviewed
发现一个小问题，github.sha 取到的是这个 PR 的第一个提交 ID。建议把中文注释改成英文，或是移除

2021-02-17 00:23 UTC, AkinoKaede reviewed
@JimhHan 1.16 下 test 似乎有点小问题

2021-02-17 01:16 UTC, AkinoKaede approved these changes
LGTM

2021-02-20 08:40 UTC, JimhHan approved these changes

2021-03-02 13:52 UTC, rprx approved these changes

2021-03-02 14:46 UTC, merged

2021-03-02 14:47 UTC, AkinoKaede commented
Thanks for your work.