workflow: add autorelease
XTLS/Xray-core pull request #266
Opened 2021-02-15 18:15 UTC by 1715173329

为 Release 自动构建二进制文件并上传

效果演示：
[1715173329/action/569311543](https://github.com/1715173329/Xray-core/actions/runs/569311543)
[1715173329/tag/v19.19.810](https://github.com/1715173329/Xray-core/releases/tag/v19.19.810)

2021-02-15 23:36 UTC, AkinoKaede requested changes
需要将文件修改时间重置为 UTC 2021-01-01 00:00:00
非 Release 可以将 Custom 改为 commit id 以区分

2021-02-16 04:34 UTC, 1715173329 commented
> 需要将文件修改时间重置为 UTC 2021-01-01 00:00:00

包括 xray 在内的二进制文件？有何必要？

> 非 Release 可以将 Custom 改为 commit id 以区分

该 action 的触发条件仅为 Release，非 Release 不会进行构建

2021-02-16 04:35 UTC, AkinoKaede commented
> > 需要将文件修改时间重置为 UTC 2021-01-01 00:00:00
> 
> 包括 xray 在内的二进制文件？有何必要？
> 
> > 非 Release 可以将 Custom 改为 commit id 以区分
> 
> 该 action 的触发条件仅为 Release，非 Release 不会进行构建

第一点是 rprx 的要求，我也不清楚具体原因…

2021-02-16 06:38 UTC, 1715173329 commented
@AkinoKaede Updated.

2021-02-16 18:17 UTC, 1715173329 commented
golang 已释放 1.16 正式版本

2021-02-17 00:34 UTC, AkinoKaede approved these changes

2021-03-02 13:54 UTC, rprx commented
感谢 PR，目前 https://github.com/XTLS/Xray-core/pull/251 更符合当前的发布流程，也经过了更多人的审核

这个 PR 再完善一些后可以作为自动编译脚本

2021-03-02 14:01 UTC, 1715173329 commented
> 这个 PR 再完善一些后可以作为自动编译脚本

好的，希望您可以提出修改意见。

2022-06-07 15:19 UTC, closed without merging