custom tfo queue length support
XTLS/Xray-core pull request #310
Opened 2021-02-27 00:27 UTC by risetechlab

调用setsockopt(..., TCP_FASTOPEN, ...)时，传入的int参数，代表处于TCP_SYN_RECV状态的TFO上限，[include/net/request_sock.h:140](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/net/request_sock.h?h=v5.11.2#n140)：
```
struct fastopen_queue {
	...
	spinlock_t	lock;
	int		qlen;		/* # of pending (TCP_SYN_RECV) reqs */
	int		max_qlen;	/* != 0 iff TFO is currently enabled */
        ...
};
```
此队列长度在此程序的代码中固定设定为1，如果一瞬间有多个TFO SYN送到服务端，那仅有一个TFO能成功被处理，而别的会因TFO Listen Overflow回退到普通的TCP三次握手，[net/ipv4/tcp_fastopen.c:335](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/ipv4/tcp_fastopen.c?h=v5.11.2#n335)：
```
	if (fastopenq->qlen >= fastopenq->max_qlen) {
		...
		if (!req1 || time_after(req1->rsk_timer.expires, jiffies)) {
			__NET_INC_STATS(sock_net(sk),
					LINUX_MIB_TCPFASTOPENLISTENOVERFLOW);
			...
			return false;
		}
		...
	}
```

此pull request在配置文件的sockopt中增加了一个int32类型的tcpFastOpenQLen，用于指定此队列的长度，以避免overflow：
```
                "sockopt": {
                    "tcpFastOpen": true,
                    "tcpFastOpenQLen": 512 // 队列长度设定为512
                }
```
如果启用了TFO，且未指定此值或者此值<1，则取默认值1。

2021-03-05 08:51 UTC, rprx commented
我们应该可以使 `tcpFastOpen` 这个参数同时接收 bool 或 uint32

2021-03-05 08:55 UTC, rprx commented
简单来说就是在解析 JSON 时用一些技巧（可以先验证一下 true/false 能不能直接用于 uint32）

2021-03-06 04:09 UTC, risetechlab commented
你好，
最新的commit 9b81740让tcpFastOpen同时接受boolean和numeric，去掉了上一个commit添加的tcpFastOpenQLen参数。

2021-03-06 04:32 UTC, rprx commented on transport/internet/sockopt_linux.go
> +			tfo = 1
这里？

2021-03-06 04:35 UTC, risetechlab commented on transport/internet/sockopt_linux.go
> +			tfo = 1
infra/conf/transport_internet.go的464行：https://github.com/XTLS/Xray-core/pull/310/files#diff-f898f86523782721aa861d5d5f610608420ae29acf3a27eb71fa618590179d19R464

2021-03-06 04:52 UTC, rprx commented on transport/internet/sockopt_linux.go
> +			tfo = 1
也就是说只有 inbound 才需要 1 以上的值对吧（本来以为是有某种协商）

2021-03-06 05:03 UTC, risetechlab commented on transport/internet/sockopt_linux.go
> +			tfo = 1
对的，OUTBOUND如果传大于1的值会报错[net/ipv4/tcp.c?h=v5.11.3#n3540](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/ipv4/tcp.c?h=v5.11.3#n3540)：
```
	case TCP_FASTOPEN_CONNECT:
		if (val > 1 || val < 0) {
			err = -EINVAL;
		}
```
客户端传1就可以代表启用，启用后，SYN会延迟到write()调用再发送[net/ipv4/tcp_ipv4.c?h=v5.11.3#n307](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/ipv4/tcp_ipv4.c?h=v5.11.3#n307)。

2021-03-06 08:42 UTC, rprx commented
目前的代码看上去没有问题，实测可行吗

另外可能需要修一下 test

2021-03-06 11:23 UTC, AkinoKaede requested changes
`transport/internet/sockopt_windows.go` 需要修一下

2021-03-06 12:10 UTC, risetechlab commented
嗯，测试过确定是有效果的。

服务器和客户端通过/proc/net/stat可以查看：
```
grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 85-92 | column -t
```
输出里面有一列TCPFastOpenActiveFail和TCPFastOpenListenOverflow，如果服务器上的INBOUND启用TFO后，没有把queue length，也就是INBOUND那里的调用setsockopt()传入的整数值改成1以上的话，客户端走这个INBOUND发起多个TCP连接，例如访问个加载了好几个域名的css、js和图片的网页，服务器上的这个TCPFastOpenListenOverflow数值就会有明显增加，客户端通过同样的命令，也可以看到TCPFastOpenActiveFail这个计数器的值增加，特别是没启用mux的话。
如果把queue length，TCPFastOpenListenOverflow和TCPFastOpenActiveFail计数器就基本不会增加了。
如果抓包，具体体现是，SYN TFO成功的，服务器响应的SYN ACK number是包含了data部分，如果SYN TFO失败，响应的SYN ACK number只是SYN的seq+1。

2021-03-06 12:22 UTC, rprx commented
需要改一下 `sockopt_windows.go` 和 `sockopt_darwin.go` 的代码

2021-03-06 12:49 UTC, AkinoKaede approved these changes

2021-03-06 12:52 UTC, rprx commented on transport/internet/sockopt_darwin.go
> +		if config.Tfo >= 0 {
这里也可以直接用 `tfo` 吧

2021-03-06 13:05 UTC, rprx commented on infra/conf/transport_internet.go
> +				tfo = 1
这里和 test 都改为 256 吧

2021-03-06 13:54 UTC, risetechlab commented
> 需要改一下 `sockopt_windows.go` 和 `sockopt_darwin.go` 的代码

忘了那两个系统了，不好意思，也奇怪咋会有check不通过，没想起来还有个darwin和windows的sockopt。
最新的commit已经完善好了，MacOS上Server的queue length是单独通过内核参数net.inet.tcp.fastopen_backlog指定的，Windows的话我还的确不太了解，官方接口文档显示代表的是boolean类型，应该就是就按原来那样传1和0。
刚刚MacOS上的test不通过，日志里面看到是”--- FAIL: TestVMessKCP (11.08s)“，有点迷，看了半天没看出什么问题，force push重新运行一次test又成功了，汗。
最新的commit c007d70 test和默认的TFO queue length都已经改成256了。

2021-03-06 14:00 UTC, rprx commented on transport/internet/sockopt_darwin.go
> +		if config.Tfo >= 0 {
目前只剩这里了

2021-03-06 14:03 UTC, risetechlab commented on transport/internet/sockopt_darwin.go
> +		if config.Tfo >= 0 {
MacOS这个传固定值就好了，queue length是通过内核参数net.inet.tcp.fastopen_backlog设定的。

2021-03-06 14:13 UTC, rprx commented on transport/internet/sockopt_darwin.go
> +		if config.Tfo >= 0 {
> 
> 
> MacOS这个传固定值就好了，queue length是通过内核参数net.inet.tcp.fastopen_backlog设定的。

指第 22 行

2021-03-06 14:18 UTC, risetechlab commented on transport/internet/sockopt_darwin.go
> +		if config.Tfo >= 0 {
> > MacOS这个传固定值就好了，queue length是通过内核参数net.inet.tcp.fastopen_backlog设定的。
> 
> 指第 22 行

天，我没发现！新的commit修正了。

2021-03-06 14:45 UTC, merged

2021-03-06 14:46 UTC, rprx commented
感谢 PR，麻烦补充一下文档（Linux Server 上 `true` 时的默认值，以及可以指定数值）