fix grpc dial ipv6 address
XTLS/Xray-core pull request #476
Opened 2021-04-04 11:12 UTC by lucifer9

Now dial using the proper IPv6 address (without []).

2021-04-04 11:23 UTC, JimhHan requested changes

2021-04-04 11:23 UTC, JimhHan commented on transport/internet/grpc/dial.go
> +		gonet.JoinHostPort(dest.Address.IP().String(), dest.Port.String()),
dest.Address 有可能为 `domainAddress`

2021-04-04 11:50 UTC, lucifer9 commented on transport/internet/grpc/dial.go
> +		gonet.JoinHostPort(dest.Address.IP().String(), dest.Port.String()),
You are right.

2021-04-04 15:47 UTC, AkinoKaede approved these changes

2021-04-05 00:44 UTC, JimhHan approved these changes

2021-04-05 01:00 UTC, merged

2021-04-06 04:32 UTC, AkinoKaede commented
Thanks for your work